
namespace Rhit.Applications.Models.Services {
    public enum RequestType {
        NodeDeletion,
        NodeCreation,
        AllLocations,
        CampusServices,
        CampusServicesUpdate,
        CampusServicesVersionUpdate,
        ChangeCorners,
        DeleteLocation,
        Directions,
        IncrementVersion,
        InternalLocations,
        Location,
        LocationCreation,
        LocationSearch,
        LocationUpdate,
        Login,
        MoveLocation,
        PathData,
        TopLocations,
        Tags,
        Tours,
        Version,
        PathCreation,
        PathDeletion,
        NodeUpdate,
    }
}
