
namespace Rhit.Applications.Models.Services {
    public enum ResponseType {
        NodeUpdate,
        NodeDeletion,
        NodeCreation,
        AllLocations,
        CampusServices,
        CampusServicesUpdate,
        CampusServicesVersionUpdate,
        ChangeCorners,
        ConnectionError,
        DeleteLocation,
        Directions,
        IncrementVersion,
        InternalLocations,
        Location,
        LocationCreation,
        LocationsSearch,
        LocationUpdate,
        Login,
        MoveLocation,
        PathData,
        ServerError,
        TopLocations,
        Tags,
        Tours,
        Version,
        PathCreation,
        PathDeletion,
    }
}