//
//  RHAnnotationView.h
//  RHIT Mobile Campus Directory
//
//  Copyright 2011 Rose-Hulman Institute of Technology
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

#import <MapKit/MapKit.h>


@class RHMapLabel;
@class RHAnnotation;
@class RHAnnotationViewDelegate;

/// \ingroup map
/// The actual view to be rendered when an RHAnnotation appears on the map.
@interface RHAnnotationView : MKAnnotationView

/// Delegate responsible for responding to events and requests generated by
/// this RHAnnotationView.
@property (nonatomic, retain) RHAnnotationViewDelegate *delegate;

/// Annotation storing the data we're looking for. This is simply a proxy to
/// the standard MKAnnotationView "annotation" property, just casted to be more
/// useful here.
@property (nonatomic, readonly) RHAnnotation *storedAnnotation;

/// Special label that emulates the MapKit look and feel. This label will
/// display the name of the relevant location when the map view is at an
/// appropriate zoom level.
@property (nonatomic, retain) RHMapLabel *textView;

/// Signal this RHAnnotationView to check its annotation's visibility property,
/// updating its label's visibility appropriately. This method will be called
/// by this RHAnnotationView's RHAnnotation when the RHAnnotation is notified
/// of a zoom level change.
- (void)updateAnnotationVisibility;

@end