//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHITMobile.RhitPrivate {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expiration {
            get {
                return this.ExpirationField;
            }
            set {
                if ((this.ExpirationField.Equals(value) != true)) {
                    this.ExpirationField = value;
                    this.RaisePropertyChanged("Expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure.Data")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdvisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MailboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Advisor {
            get {
                return this.AdvisorField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvisorField, value) != true)) {
                    this.AdvisorField = value;
                    this.RaisePropertyChanged("Advisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mailbox {
            get {
                return this.MailboxField;
            }
            set {
                if ((this.MailboxField.Equals(value) != true)) {
                    this.MailboxField = value;
                    this.RaisePropertyChanged("Mailbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Major {
            get {
                return this.MajorField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorField, value) != true)) {
                    this.MajorField = value;
                    this.RaisePropertyChanged("Major");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
    [System.SerializableAttribute()]
    public partial class AuthFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure.Data")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EnrolledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char FinalDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinalRoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxEnrollmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RHITMobile.RhitPrivate.CourseTime[] ScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CRN {
            get {
                return this.CRNField;
            }
            set {
                if ((this.CRNField.Equals(value) != true)) {
                    this.CRNField = value;
                    this.RaisePropertyChanged("CRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Enrolled {
            get {
                return this.EnrolledField;
            }
            set {
                if ((this.EnrolledField.Equals(value) != true)) {
                    this.EnrolledField = value;
                    this.RaisePropertyChanged("Enrolled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char FinalDay {
            get {
                return this.FinalDayField;
            }
            set {
                if ((this.FinalDayField.Equals(value) != true)) {
                    this.FinalDayField = value;
                    this.RaisePropertyChanged("FinalDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalHour {
            get {
                return this.FinalHourField;
            }
            set {
                if ((this.FinalHourField.Equals(value) != true)) {
                    this.FinalHourField = value;
                    this.RaisePropertyChanged("FinalHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalRoom {
            get {
                return this.FinalRoomField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalRoomField, value) != true)) {
                    this.FinalRoomField = value;
                    this.RaisePropertyChanged("FinalRoom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instructor {
            get {
                return this.InstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorField, value) != true)) {
                    this.InstructorField = value;
                    this.RaisePropertyChanged("Instructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxEnrollment {
            get {
                return this.MaxEnrollmentField;
            }
            set {
                if ((this.MaxEnrollmentField.Equals(value) != true)) {
                    this.MaxEnrollmentField = value;
                    this.RaisePropertyChanged("MaxEnrollment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RHITMobile.RhitPrivate.CourseTime[] Schedule {
            get {
                return this.ScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleField, value) != true)) {
                    this.ScheduleField = value;
                    this.RaisePropertyChanged("Schedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Term {
            get {
                return this.TermField;
            }
            set {
                if ((this.TermField.Equals(value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseTime", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure.Data")]
    [System.SerializableAttribute()]
    public partial class CourseTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartPeriodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndPeriod {
            get {
                return this.EndPeriodField;
            }
            set {
                if ((this.EndPeriodField.Equals(value) != true)) {
                    this.EndPeriodField = value;
                    this.RaisePropertyChanged("EndPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartPeriod {
            get {
                return this.StartPeriodField;
            }
            set {
                if ((this.StartPeriodField.Equals(value) != true)) {
                    this.StartPeriodField = value;
                    this.RaisePropertyChanged("StartPeriod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserEnrollment", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure.Data")]
    [System.SerializableAttribute()]
    public partial class UserEnrollment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TermField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CRN {
            get {
                return this.CRNField;
            }
            set {
                if ((this.CRNField.Equals(value) != true)) {
                    this.CRNField = value;
                    this.RaisePropertyChanged("CRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Term {
            get {
                return this.TermField;
            }
            set {
                if ((this.TermField.Equals(value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomSchedule", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure.Data")]
    [System.SerializableAttribute()]
    public partial class RoomSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TermField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CRN {
            get {
                return this.CRNField;
            }
            set {
                if ((this.CRNField.Equals(value) != true)) {
                    this.CRNField = value;
                    this.RaisePropertyChanged("CRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndPeriod {
            get {
                return this.EndPeriodField;
            }
            set {
                if ((this.EndPeriodField.Equals(value) != true)) {
                    this.EndPeriodField = value;
                    this.RaisePropertyChanged("EndPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartPeriod {
            get {
                return this.StartPeriodField;
            }
            set {
                if ((this.StartPeriodField.Equals(value) != true)) {
                    this.StartPeriodField = value;
                    this.RaisePropertyChanged("StartPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Term {
            get {
                return this.TermField;
            }
            set {
                if ((this.TermField.Equals(value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerState", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
    [System.SerializableAttribute()]
    public partial struct ServerState : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveUserCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUpdateQueuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastRecordsAffectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan UptimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveRequests {
            get {
                return this.ActiveRequestsField;
            }
            set {
                if ((this.ActiveRequestsField.Equals(value) != true)) {
                    this.ActiveRequestsField = value;
                    this.RaisePropertyChanged("ActiveRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveUserCount {
            get {
                return this.ActiveUserCountField;
            }
            set {
                if ((this.ActiveUserCountField.Equals(value) != true)) {
                    this.ActiveUserCountField = value;
                    this.RaisePropertyChanged("ActiveUserCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUpdateQueued {
            get {
                return this.IsUpdateQueuedField;
            }
            set {
                if ((this.IsUpdateQueuedField.Equals(value) != true)) {
                    this.IsUpdateQueuedField = value;
                    this.RaisePropertyChanged("IsUpdateQueued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastRecordsAffected {
            get {
                return this.LastRecordsAffectedField;
            }
            set {
                if ((this.LastRecordsAffectedField.Equals(value) != true)) {
                    this.LastRecordsAffectedField = value;
                    this.RaisePropertyChanged("LastRecordsAffected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateTime {
            get {
                return this.LastUpdateTimeField;
            }
            set {
                if ((this.LastUpdateTimeField.Equals(value) != true)) {
                    this.LastUpdateTimeField = value;
                    this.RaisePropertyChanged("LastUpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestCount {
            get {
                return this.RequestCountField;
            }
            set {
                if ((this.RequestCountField.Equals(value) != true)) {
                    this.RequestCountField = value;
                    this.RaisePropertyChanged("RequestCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Uptime {
            get {
                return this.UptimeField;
            }
            set {
                if ((this.UptimeField.Equals(value) != true)) {
                    this.UptimeField = value;
                    this.RaisePropertyChanged("Uptime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mobileprivate.rose-hulman.edu", ConfigurationName="RhitPrivate.IWebService")]
    public interface IWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/Login", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/LoginResponse")]
        RHITMobile.RhitPrivate.AuthenticationResponse Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://mobileprivate.rose-hulman.edu/IWebService/Logout")]
        void Logout(string authToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/GetUser", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/GetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/GetUserAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        RHITMobile.RhitPrivate.User GetUser(string authToken, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/SearchUsers", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/SearchUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/SearchUsersAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        RHITMobile.RhitPrivate.User[] SearchUsers(string authToken, string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/GetCourse", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        RHITMobile.RhitPrivate.Course GetCourse(string authToken, int term, int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/SearchCourses", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/SearchCoursesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/SearchCoursesAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        RHITMobile.RhitPrivate.Course[] SearchCourses(string authToken, string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseEnrollment", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseEnrollmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseEnrollmentAuthFaultFaul" +
            "t", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        string[] GetCourseEnrollment(string authToken, int term, int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/GetUserEnrollment", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/GetUserEnrollmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/GetUserEnrollmentAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        RHITMobile.RhitPrivate.UserEnrollment[] GetUserEnrollment(string authToken, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseSchedule", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseScheduleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/GetCourseScheduleAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        RHITMobile.RhitPrivate.CourseTime[] GetCourseSchedule(string authToken, int term, int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/GetRoomSchedule", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/GetRoomScheduleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RHITMobile.RhitPrivate.AuthFault), Action="http://mobileprivate.rose-hulman.edu/IWebService/GetRoomScheduleAuthFaultFault", Name="AuthFault", Namespace="http://schemas.datacontract.org/2004/07/RHITMobile.Secure")]
        RHITMobile.RhitPrivate.RoomSchedule[] GetRoomSchedule(string authToken, string room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/RequestUpdate", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/RequestUpdateResponse")]
        bool RequestUpdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mobileprivate.rose-hulman.edu/IWebService/GetState", ReplyAction="http://mobileprivate.rose-hulman.edu/IWebService/GetStateResponse")]
        RHITMobile.RhitPrivate.ServerState GetState();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceChannel : RHITMobile.RhitPrivate.IWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<RHITMobile.RhitPrivate.IWebService>, RHITMobile.RhitPrivate.IWebService {
        
        public WebServiceClient() {
        }
        
        public WebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RHITMobile.RhitPrivate.AuthenticationResponse Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public void Logout(string authToken) {
            base.Channel.Logout(authToken);
        }
        
        public RHITMobile.RhitPrivate.User GetUser(string authToken, string username) {
            return base.Channel.GetUser(authToken, username);
        }
        
        public RHITMobile.RhitPrivate.User[] SearchUsers(string authToken, string search) {
            return base.Channel.SearchUsers(authToken, search);
        }
        
        public RHITMobile.RhitPrivate.Course GetCourse(string authToken, int term, int crn) {
            return base.Channel.GetCourse(authToken, term, crn);
        }
        
        public RHITMobile.RhitPrivate.Course[] SearchCourses(string authToken, string search) {
            return base.Channel.SearchCourses(authToken, search);
        }
        
        public string[] GetCourseEnrollment(string authToken, int term, int crn) {
            return base.Channel.GetCourseEnrollment(authToken, term, crn);
        }
        
        public RHITMobile.RhitPrivate.UserEnrollment[] GetUserEnrollment(string authToken, string username) {
            return base.Channel.GetUserEnrollment(authToken, username);
        }
        
        public RHITMobile.RhitPrivate.CourseTime[] GetCourseSchedule(string authToken, int term, int crn) {
            return base.Channel.GetCourseSchedule(authToken, term, crn);
        }
        
        public RHITMobile.RhitPrivate.RoomSchedule[] GetRoomSchedule(string authToken, string room) {
            return base.Channel.GetRoomSchedule(authToken, room);
        }
        
        public bool RequestUpdate() {
            return base.Channel.RequestUpdate();
        }
        
        public RHITMobile.RhitPrivate.ServerState GetState() {
            return base.Channel.GetState();
        }
    }
}
