201110
2180|ECE151-01|Persevering 3Rd Generation Project|WIEGAND|2|W/3/E267|F/3/C251|23|27|&nbsp|Wiegand, Frances F
3561|ECE296-01|Virtual Multi-Tasking Methodology|WIEGAND|1|MTRF/7/M278|M/1/C221|17|1|&nbsp|Wiegand, Frances F
3748|BIO315-02|Enterprise-Wide Homogeneous Encryption|WIEGAND|1|TWF/4/O125|T/1/G200|20|14|&nbsp|Wiegand, Frances F
3352|BIO315-01|Enterprise-Wide Homogeneous Encryption|REILLY|1|MTRF/1/C287|T/1/G200|21|14|&nbsp|Reilly, Vivien Gavin
3482|BE381-01|Phased Intangible Application|JAST|3|MWT/8/A393|R/3/E382|24|6|Permission of instructor required|Jast, Marcel Lora
