201130
2018|ME272-01|Cross-Platform Didactic Product|WIEGAND|3|MTRF/1/D151|T/1/M103|35|18|&nbsp|Wiegand, Frances F
2782|MA257-01|User-Friendly Mission-Critical Graphical User Interface|LEGROS|3|MTRF/4-7/B379|W/1/E163|29|29|&nbsp|Legros, Leila Alden
3174|GRAD150-01|Automated 6Th Generation Toolset|LEGROS|1|MTRF/1/D310|F/2/A352|30|17|&nbsp|Legros, Leila Alden
3076|ME136-01|Exclusive 5Th Generation Graphical User Interface|ZIEME|3|MWT/3/A284|M/3/M264|34|20|&nbsp|Zieme, Candido S
3056|EGMT139-01|Robust Uniform Service-Desk|JAST|3|W/1-2/G100|T/2/O283|32|7|&nbsp|Jast, Marcel Lora
