201120
2431|MS395-01|Switchable 6Th Generation Forecast|LEGROS|5|W/2/B349|F/2/F202|27|15|&nbsp|Legros, Leila Alden
3416|EGMT300-01|De-Engineered Incremental Application|REYNOLDS|3|TWF/1/D188|T/1/B263|29|6|Second year students only|Reynolds, Nathaniel Elza
2728|SV148-01|Focused Hybrid Capability|SCHROEDER|2|MTRF/6/B213|M/3/E118|24|21|&nbsp|Schroeder, Rasheed Jacklyn
2965|JP250-01|Cross-Group Scalable Synergy|SENGER|4|MTRF/1/O273|F/2/B278|30|25|&nbsp|Senger, Marcelo Aracely
2759|IA212-01|Re-Contextualized Intermediate Process Improvement|SENGER|3|MTRF/4-7/D278|T/2/D221|32|15|&nbsp|Senger, Marcelo Aracely
