201210
2598|GRAD264-01|Centralized Stable Capability|WIEGAND|2|MTRF/5/E148:F/2/M328|W/2/D263|39|4|&nbsp|Wiegand, Frances F
2800|BE388-01|Progressive Empowering Initiative|KRIS|4|W/2/O362|F/3/O395|37|10|&nbsp|Kris, Lavinia H
3836|AB303-01|Reverse-Engineered Incremental Circuit|LEGROS|1|MWT/3/F103|R/2/C310|40|18|&nbsp|Legros, Leila Alden
2578|BE388-02|Progressive Empowering Initiative|LEGROS|4|MWT/3-7/D314|F/3/O395|39|10|&nbsp|Legros, Leila Alden
2375|ECE264-01|Mandatory Didactic Open Architecture|DUBUQUE|2|MTRF/2/F286|M/2/G250|35|23|&nbsp|DuBuque, Christophe Lydia
