201230
2346|CE196-01|Phased Systemic Implementation|KOHLER|2|W/3/F238:R/2/F213|F/1/E322|42|22|&nbsp|Kohler, Dixie Yesenia
3355|CHE223-01|Cross-Group Neutral Definition|ANDERSON|3|MTRF/9-10/M241|R/2/A385|43|25|"Quoted" co"m\|ment|Anderson, Kellie O
3524|AB164-01|Optional 3Rd Generation Synergy|REILLY|3|MTRF/2/C200|W/3/B370|53|13|&nbsp|Reilly, Vivien Gavin
2621|GE256-01|Fundamental Well-Modulated Migration|ANDERSON|4|TWF/8-10/D383|R/1/D231|42|15|&nbsp|Anderson, Kellie O
2471|CSSE371-01|Sharable Next Generation Hub|REILLY|5|MTRF/9/G366|R/2/A236|43|6|&nbsp|Reilly, Vivien Gavin
