201220
3775|IA290-01|Visionary Reciprocal Infrastructure|SENGER|3|MTRF/5/B235|M/1/D111|39|12|&nbsp|Senger, Marcelo Aracely
3335|GS391-01|Profound Grid-Enabled Approach|REYNOLDS|5|MTRF/3-9/G380|M/2/O249|41|6|&nbsp|Reynolds, Nathaniel Elza
2720|BIO229-01|Diverse Fault-Tolerant Website|SENGER|1|MWT/2/O119|R/1/E156|38|29|&nbsp|Senger, Marcelo Aracely
3458|CE329-02|Innovative Zero Defect Flexibility|REYNOLDS|1|TBA/TBA/TBA|T/3/D233|34|17|&nbsp|Reynolds, Nathaniel Elza
2212|CE329-01|Innovative Zero Defect Flexibility|LEGROS|1|MWT/2/A354|T/3/D233|48|17|&nbsp|Legros, Leila Alden
